apiVersion: v1
kind: Service
metadata:
  name: django-entrypoint
  namespace: default
spec:
  selector:
    app: django
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
