apiVersion: v1
kind: Service
metadata:
  name: django-entrypoint-2
  namespace: default
spec:
  selector:
    app: djangoapp
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
