apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-applikasjon-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      containers:
      - name: django-applikasjon-2
        image: sjohans1/django-bachelor:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAVN
          value: bachelor_db
        - name: DB_ROOT_USER
          value: root
        - name: DB_ROOT_PASS
          value: cGFzc3dvcmQK
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        
