apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-applikasjon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api
  template:
    metadata:
      labels:
        type: api
    spec:
      containers:
      - name: django-applikasjon
        image: django-applikasjon:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: django-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    type: api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
