apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-applikasjon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-applikasjon
        image: django-applikasjon:latest
        imagePullPolicy: Never

