# Generated by Django 4.0.1 on 2022-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidspunkt', models.IntegerField(default=0)),
                ('intervall', models.IntegerField(default=0)),
                ('tid_siden_siste', models.IntegerField(default=0)),
            ],
        ),
    ]
