# Generated by Django 4.0.1 on 2022-02-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdb',
            name='tid',
            field=models.CharField(default='', max_length=75),
        ),
    ]
