apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: django-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-applikasjon
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
