apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    role: webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      role: webserver
    
  strategy:
  type: RollingUpdate
  rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 50%    
  template:
    metadata:
      labels:
        role: webserver
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
